name: tag
run-name: Creating Tag
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["sdk"]
    types: [completed]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    environment: Main

    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install .[dev]

      - name: Set curreny version value
        run: |
          cartesapp_version=$(python -c "from importlib.metadata import version;print(version('cartesapp'))")
          echo Setting Version Var: $cartesapp_version
          echo "cartesapp_version=$cartesapp_version" >> "$GITHUB_ENV"

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ env.cartesapp_version }}',
              sha: context.sha
            })
